trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: templates
      type: github
      name: micro-business/templates
      endpoint: micro-business

name: $(GitVersion.SemVer)

steps:
  - template: build/steps/gitversion.yml@templates
  - task: Docker@2
    displayName: Test and Coverage
    inputs:
      command: "build"
      Dockerfile: "$(system.defaultWorkingDirectory)/docker/Dockerfile.testAndCoverage"
      buildContext: "$(system.defaultWorkingDirectory)"
      arguments: "--build-arg CI_SERVICE=$(CI_SERVICE) --build-arg COVERALLS_TOKEN=$(COVERALLS_TOKEN)"
