trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: gitversion/setup@0
    displayName: "Setting up GitVersion"
    inputs:
      versionSpec: "5.x"

  - task: gitversion/execute@0
    displayName: "Figure out GitVersion"
    inputs:
      configFilePath: "./GitVersion.yml"

  - task: Docker@2
    displayName: Test and Coverage
    inputs:
      command: "build"
      Dockerfile: "$(system.defaultWorkingDirectory)/docker/Dockerfile.testAndCoverage"
      buildContext: "$(system.defaultWorkingDirectory)"
      arguments: "--build-arg CI_SERVICE=$(CI_SERVICE) --build-arg COVERALLS_TOKEN=$(COVERALLS_TOKEN)"
